excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Yaadwinder.github.io
name: yadwinderdeepness.com
description: behind the mind
author: Yaadwinder
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: yadwinderdeepness.com
ga_tracking_id: 